name:  CI&CD setup
on:
  push:  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install yarn dependencies
        run: yarn install
      - name: Run build task
        run: yarn build:staging
      - name: Deploy to AWS
        uses: ShauryaAg/AWS-Deploy-action@v1

      # - name: Deploy to Server 1
      #   uses: aws-actions/configure-aws-credentials@v1
        #  easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}